---
title: "My English Activity Log : M.E.A.L."
author:
  - name: Julie Cantineau
date: 09-16-2019
categories: 
  - M.E.A.L.
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Here is all activies I will do or I've done in english, in a chronological order with sometimes few lines to comment them and why not give advices for some categories.

**Movies and Series :** 

02/02 : I start watching "The chilling adventure of Sabrina"

20/12 : I watched the two first episodes of the serie "the witcher", it's a netflix adaptation of the same called books. The serie is situated at the time of books, so before the 3 video games also called The Witcher.3

12/12 : I watched the second episode of the new Netflix series V Wars

10/12 : I watched the first episode of V wars which is a vampire serie but it isn't as habitual with poor kind vampire who are rejected by society. Here this is vampire infected by prions who aren't nice.

01/12 : I watched a short episode of a serie called "En bref" on Netflix. The first episode was about diamond and explained how it appeared and why there are so expensive.

11/10 : watching Matrix 2

10/11 : watching Matrix on Netflix also for the first time. Despite it's a pretty old movie and therefore the 3D images have not aged very well, it's a movie that you have to watch once in life (for all references in pop culture)

01/11 : watching Gladiator on Netflix for the first time, it was a really good movie and the end was emotional, giving a real definition of hero

31/10 : watching an episode of Lucifer on Netflix (season 1)

30/10 : watching an episode of Lucifer (season 1)

04/10 : watching an episode of Orange is the new black (season 3)

**Books :** 

**Speaking :**

13/10 : My mum and I made a facetime with a British friend

31/10 : I spoke with my neighbours from SHAPE

08/10 : I spoke with a British friend by video call

29/09 : I spoke with a British friend by video call

**Newspapers :**

16/02 : Checking the BBC news for the english course

02/02 : Checking the BBC news for the english course

01/12 : Checking the BBC news for the english course

24/11 : Checking the BBC news for the english course

17/11 : Checking the BBC news for the english course

03/11 : Checking the BBC news for the english course

20/10 : Checking the BBC news for the english course

13/10 : checking the BBC news for the english course

06/10 : checking the BBC news for the english course

**Podcasts :**

09/11 : I listened to a short documentary in english on youtube chanel "France 24" about the different french regional accents and the sentiment of pride that it produces as well as a certain form of discrimation

**Games :**

02/12  I played: LyricsTraining for 15 minutes

11/11 : I played LyricsTraining for 20 minutes

10/11 : I played LyricsTraining for almost one hour

09/11 : I introduced LyricsTraining to my boyfriend and we played for 20 minutes

18/10 : I played "LyricsTraining" for 30 minutes 

**Other :**

13/12 : I went to the master1 biologists english presentation with their posters. 

01/11 : I watched the opening ceremony of the Blizzcon 2019 (Its happened in California, It's a annual convention of the compagny "Blizzard Entertainment" during they present novelties for their current games and those coming out soon. The entirely ceremony is in english with no subtitles.)

