---
title: "My english activity log"
---

Here is all activies I will do or I've done in english, in a chronological order with sometimes few lines to comment them and why not give advices for some categories.

**Movies and Series :** 

31/10 : watching an episode of Lucifer on Netflix (season 1)

30/10 : watching an episode of Lucifer (season 1)

04/10 : watching an episode of Orange is the new black (season 3)

**Books :** 

**Speaking :**

31/10 : speaking with my neighbours from SHAPE

08/10 : Speaking with a British friend by video call

29/09 : Speaking with a British friend by video call

**Newspapers :**

03/11 : Checking the BBC news for the english course

20/10 : Checking the BBC news for the english course

13/10 : checking the BBC news for the english course

06/10 : checking the BBC news for the english course

**Podcasts :**

**Games :**

18/10 : Playing "LyricsTraining" for 30 minutes 

**Other :**

01/11 : Watching the opening ceremony of the Blizzcon 2019 (Its happened in California, It's a annual convention of the compagny "Blizzard Entertainment" during they present novelties for their current games and those coming out soon. The entirely ceremony is in english with no subtitles.)


