---
title: "Article 5 : Antibiotic-resistant bacteria more prevalent in device-related infections"
description: 
author:
  - name: Julie Cantineau
    url: {}
date: 12-17-2019
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Source of the article with publication date and word count

Source of the article : <https://www.sciencedaily.com/releases/2019/11/191125100408.htm>
(25/11/2019)

Word count : 417

## Vocabulary 

| Words from the text | Synonym/explanation in English | French translation |
| ------------------- | ------------------------------ | -----------------|
| Among   | in the midst of | au milieu de |
| To ensure   | to secure | assurer, garantir | 


## Analysis table 

|                              |                                                                     |
| ---------------------------- | ------------------------------------------------------------------- |
| Researchers                  | Society for Healthcare Epidemiology of America            |
| Published in? When (if mentioned) ? | Infection Control & Hospital Epidemiology, 2019                                |
| General topic?               | Healthcare-associated infections (HAI's) are more inclined to be resistant to antibiotic                |
| Procedure/what was examined? | The presence of HAI's in adult and pediatric healthcare, which bacteria in causes and the effect of hospitalisation's time. |
| Conclusions/discovery?       | HAI's are more resistant if people stays for a long time at hospital.HAI's in adult services are more resistant then in pediatric services. Germs present and resistant depend on care localisation and type of infection. The three morecommon HAI's in adult are Escherichia coli, Staphylococcus areus and Klebsiella. |
| Remaining questions?         | / |



<https://www.sciencedaily.com/releases/2019/11/191125100408.htm> 
